import Head from "next/head";
import Image from "next/image";
// import { Inter } from 'next/font/google'
import styles from "@/styles/Home.module.css";
import { NextPageContext } from "next";
import { getSession, signOut, useSession } from "next-auth/react";
import { Fragment, useState } from "react";
import { Dialog, Transition } from "@headlessui/react";
import { HiOutlineHome, HiHome } from "react-icons/hi";
import { MdSubscriptions, MdHistory, MdSearch } from "react-icons/md";
import Link from "next/link";
import Input from "@/components/Input";
import Jumbotron from "@/components/Jumbotron";
import VideoList from "@/components/VideoList";
import { useRouter } from "next/router";

// const inter = Inter({ subsets: ['latin'] })

// export async function getServerSideProps(context: NextPageContext) {
//   const session = await getSession(context);

//   if (!session) {
//     return {
//       redirect: {
//         destination: "/auth",
//         permanent: false,
//       },
//     };
//   }

//   return {
//     props: {},
//   };
// }
export default function Home() {
  // width and height if screen is less than 768px
  const [width, setWidth] = useState(100);
  const [height, setHeight] = useState(100);

  // handle screen size
  // const dynamicWidth = window;
  // const dynamicHeight = window;

  return (
    <>
      <Head>
        <title>Ocra | Home</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <>
        <input
          type="text"
          className="bg-[#161D2F]  py-2 px-3 text-white rounded-md w-full"
          placeholder="Search"
        />

        <Jumbotron />
        <section className="mt-10">
          <VideoList />
        </section>
      </>
      {/* <div className="p-5 lg:ml-20  w-full">
      </div> */}
      {/* <main className=" h-screen lg:flex ">
        <aside className="bg-[#161D2F] m-0 md:m-3 rounded-md lg:fixed lg:left-0 lg:h-[calc(100vh-20px)] ">
          <nav className="p-3 flex items-center justify-between lg:flex-col  lg:h-full">
            <div>
              <div className="block ">
                <Image
                  src="/logo-onlyicon.png"
                  alt="Ocra Logo"
                  width={40}
                  height={40}
                />
              </div>
              <div className="hidden md:hidden">
                <Image
                  src="/logo.png"
                  alt="Ocra Logo"
                  width={100}
                  height={100}
                />
              </div>
            </div>
            <ul className="flex gap-10 lg:gap-20 lg:flex-col">
              <li>
                <Link href="/">
                  <HiHome className="text-white text-base md:text-lg lg:text-2xl  hover:text-white transition duration-150" />
                </Link>
              </li>
              <li>
                <Link href="/subscriptions">
                  <MdSubscriptions className="text-gray-500 text-base md:text-lg lg:text-2xl hover:text-white transition duration-150" />
                </Link>
              </li>
              <li>
                <Link href="/history">
                  <MdHistory className="text-gray-500 text-base md:text-lg lg:text-2xl hover:text-white transition duration-150" />
                </Link>
              </li>
            </ul>

            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-full bg-gray-500"></div>
              <p className="text-white hidden md:hidden">John Doe</p>
            </div>
          </nav>
        </aside>

        <div className="p-5 lg:ml-20  w-full">
          <input
            type="text"
            className="bg-[#161D2F]  py-2 px-3 text-white rounded-md w-full"
            placeholder="Search"
          />

          <Jumbotron />
          <section className="mt-10">
            <VideoList />
          </section>
        </div>
      </main> */}
    </>
  );
}
